namespace LaquaiLib.WasmServices.FileSystemProxy;

/// <summary>
/// Implements the <see cref="IPath"/> interface for use in the <see cref="IFileSystemProxy"/>.
/// </summary>
public class Path : IPath
{
    /// <inheritdoc cref="System.IO.Path.ChangeExtension(string, string)" />
    public string ChangeExtension(string path, string extension) => System.IO.Path.ChangeExtension(path, extension);
    /// <inheritdoc cref="System.IO.Path.Combine(string, string)" />
    public string Combine(string path1, string path2) => System.IO.Path.Combine(path1, path2);
    /// <inheritdoc cref="System.IO.Path.Combine(string, string, string)" />
    public string Combine(string path1, string path2, string path3) => System.IO.Path.Combine(path1, path2, path3);
    /// <inheritdoc cref="System.IO.Path.Combine(string, string, string, string)" />
    public string Combine(string path1, string path2, string path3, string path4) => System.IO.Path.Combine(path1, path2, path3, path4);
    /// <inheritdoc cref="System.IO.Path.Combine(string[])" />
    public string Combine(string[] paths) => System.IO.Path.Combine(paths);
    /// <inheritdoc cref="System.IO.Path.EndsInDirectorySeparator(ReadOnlySpan{char})" />
    public bool EndsInDirectorySeparator(ReadOnlySpan<char> path) => System.IO.Path.EndsInDirectorySeparator(path);
    /// <inheritdoc cref="System.IO.Path.EndsInDirectorySeparator(string)" />
    public bool EndsInDirectorySeparator(string path) => System.IO.Path.EndsInDirectorySeparator(path);
    /// <inheritdoc cref="System.IO.Path.GetDirectoryName(string)" />
    public string? GetDirectoryName(string path) => System.IO.Path.GetDirectoryName(path);
    /// <inheritdoc cref="System.IO.Path.GetDirectoryName(ReadOnlySpan{char})" />
    public ReadOnlySpan<char> GetDirectoryName(ReadOnlySpan<char> path) => System.IO.Path.GetDirectoryName(path);
    /// <inheritdoc cref="System.IO.Path.GetExtension(string)" />
    public string GetExtension(string path) => System.IO.Path.GetExtension(path);
    /// <inheritdoc cref="System.IO.Path.GetExtension(ReadOnlySpan{char})" />
    public ReadOnlySpan<char> GetExtension(ReadOnlySpan<char> path) => System.IO.Path.GetExtension(path);
    /// <inheritdoc cref="System.IO.Path.GetFileName(string)" />
    public string GetFileName(string path) => System.IO.Path.GetFileName(path);
    /// <inheritdoc cref="System.IO.Path.GetFileName(ReadOnlySpan{char})" />
    public ReadOnlySpan<char> GetFileName(ReadOnlySpan<char> path) => System.IO.Path.GetFileName(path);
    /// <inheritdoc cref="System.IO.Path.GetFileNameWithoutExtension(string)" />
    public string GetFileNameWithoutExtension(string path) => System.IO.Path.GetFileNameWithoutExtension(path);
    /// <inheritdoc cref="System.IO.Path.GetFileNameWithoutExtension(ReadOnlySpan{char})" />
    public ReadOnlySpan<char> GetFileNameWithoutExtension(ReadOnlySpan<char> path) => System.IO.Path.GetFileNameWithoutExtension(path);
    /// <inheritdoc cref="System.IO.Path.GetFullPath(string)" />
    public string GetFullPath(string path) => System.IO.Path.GetFullPath(path);
    /// <inheritdoc cref="System.IO.Path.GetFullPath(string, string)" />
    public string GetFullPath(string path, string basePath) => System.IO.Path.GetFullPath(path, basePath);
    /// <inheritdoc cref="System.IO.Path.GetInvalidFileNameChars()" />
    public char[] GetInvalidFileNameChars() => System.IO.Path.GetInvalidFileNameChars();
    /// <inheritdoc cref="System.IO.Path.GetInvalidPathChars()" />
    public char[] GetInvalidPathChars() => System.IO.Path.GetInvalidPathChars();
    /// <inheritdoc cref="System.IO.Path.GetPathRoot(string)" />
    public string? GetPathRoot(string path) => System.IO.Path.GetPathRoot(path);
    /// <inheritdoc cref="System.IO.Path.GetPathRoot(ReadOnlySpan{char})" />
    public ReadOnlySpan<char> GetPathRoot(ReadOnlySpan<char> path) => System.IO.Path.GetPathRoot(path);
    /// <inheritdoc cref="System.IO.Path.GetRandomFileName()" />
    public string GetRandomFileName() => System.IO.Path.GetRandomFileName();
    /// <inheritdoc cref="System.IO.Path.GetRelativePath(string, string)" />
    public string GetRelativePath(string relativeTo, string path) => System.IO.Path.GetRelativePath(relativeTo, path);
    /// <inheritdoc cref="System.IO.Path.GetTempFileName()" />
    public string GetTempFileName() => System.IO.Path.GetTempFileName();
    /// <inheritdoc cref="System.IO.Path.GetTempPath()" />
    public string GetTempPath() => System.IO.Path.GetTempPath();
    /// <inheritdoc cref="System.IO.Path.HasExtension(string)" />
    public bool HasExtension(string path) => System.IO.Path.HasExtension(path);
    /// <inheritdoc cref="System.IO.Path.HasExtension(ReadOnlySpan{char})" />
    public bool HasExtension(ReadOnlySpan<char> path) => System.IO.Path.HasExtension(path);
    /// <inheritdoc cref="System.IO.Path.IsPathFullyQualified(string)" />
    public bool IsPathFullyQualified(string path) => System.IO.Path.IsPathFullyQualified(path);
    /// <inheritdoc cref="System.IO.Path.IsPathFullyQualified(ReadOnlySpan{char})" />
    public bool IsPathFullyQualified(ReadOnlySpan<char> path) => System.IO.Path.IsPathFullyQualified(path);
    /// <inheritdoc cref="System.IO.Path.IsPathRooted(string)" />
    public bool IsPathRooted(string path) => System.IO.Path.IsPathRooted(path);
    /// <inheritdoc cref="System.IO.Path.IsPathRooted(ReadOnlySpan{char})" />
    public bool IsPathRooted(ReadOnlySpan<char> path) => System.IO.Path.IsPathRooted(path);
    /// <inheritdoc cref="System.IO.Path.Join(ReadOnlySpan{char}, ReadOnlySpan{char})" />
    public string Join(ReadOnlySpan<char> path1, ReadOnlySpan<char> path2) => System.IO.Path.Join(path1, path2);
    /// <inheritdoc cref="System.IO.Path.Join(ReadOnlySpan{char}, ReadOnlySpan{char}, ReadOnlySpan{char})" />
    public string Join(ReadOnlySpan<char> path1, ReadOnlySpan<char> path2, ReadOnlySpan<char> path3) => System.IO.Path.Join(path1, path2, path3);
    /// <inheritdoc cref="System.IO.Path.Join(ReadOnlySpan{char}, ReadOnlySpan{char}, ReadOnlySpan{char}, ReadOnlySpan{char})" />
    public string Join(ReadOnlySpan<char> path1, ReadOnlySpan<char> path2, ReadOnlySpan<char> path3, ReadOnlySpan<char> path4) => System.IO.Path.Join(path1, path2, path3, path4);
    /// <inheritdoc cref="System.IO.Path.Join(string, string)" />
    public string Join(string path1, string path2) => System.IO.Path.Join(path1, path2);
    /// <inheritdoc cref="System.IO.Path.Join(string, string, string)" />
    public string Join(string path1, string path2, string path3) => System.IO.Path.Join(path1, path2, path3);
    /// <inheritdoc cref="System.IO.Path.Join(string, string, string)" />
    public string Join(string path1, string path2, string path3, string path4) => System.IO.Path.Join(path1, path2, path3, path4);
    /// <inheritdoc cref="System.IO.Path.Join(string[])" />
    public string Join(string[] paths) => System.IO.Path.Join(paths);
    /// <inheritdoc cref="System.IO.Path.TrimEndingDirectorySeparator(string)" />
    public string TrimEndingDirectorySeparator(string path) => System.IO.Path.TrimEndingDirectorySeparator(path);
    /// <inheritdoc cref="System.IO.Path.TrimEndingDirectorySeparator(ReadOnlySpan{char})" />
    public ReadOnlySpan<char> TrimEndingDirectorySeparator(ReadOnlySpan<char> path) => System.IO.Path.TrimEndingDirectorySeparator(path);
    /// <inheritdoc cref="System.IO.Path.TryJoin(ReadOnlySpan{char}, ReadOnlySpan{char}, Span{char}, out int)" />
    public bool TryJoin(ReadOnlySpan<char> path1, ReadOnlySpan<char> path2, Span<char> destination, out int charsWritten) => System.IO.Path.TryJoin(path1, path2, destination, out charsWritten);
    /// <inheritdoc cref="System.IO.Path.TryJoin(ReadOnlySpan{char}, ReadOnlySpan{char}, ReadOnlySpan{char}, Span{char}, out int)" />
    public bool TryJoin(ReadOnlySpan<char> path1, ReadOnlySpan<char> path2, ReadOnlySpan<char> path3, Span<char> destination, out int charsWritten) => System.IO.Path.TryJoin(path1, path2, path3, destination, out charsWritten);
}
