// Generated by gen-Environment.SpecialFolders.ps1 in this directory, edit that script and re-run it, not this file

namespace LaquaiLib.Extensions
{
    public static class EnvironmentExtensions
    {
        internal static global::System.Environment.SpecialFolderOption _sfo;
        extension(Environment)
        {
            /// <summary>
            /// Gets or sets the default <see cref="global::System.Environment.SpecialFolderOption"/> value that <see cref="global::LaquaiLib.Bcl.System.SpecialFolders"/> uses to retrieve paths.
            /// </summary>
            public static global::System.Environment.SpecialFolderOption DefaultSpecialFolderOption
            {
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                get => _sfo;
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                set => _sfo = value;
            }
            public static global::LaquaiLib.Bcl.System.SpecialFolders SpecialFolders => global::LaquaiLib.Bcl.System.SpecialFolders.Instance;
        }
    }
}

namespace LaquaiLib.Bcl.System
{
    /// <summary>
    /// Provides access to the special folders of the system.
    /// </summary>
    public class SpecialFolders
    {
        public static readonly SpecialFolders Instance = new SpecialFolders();
        private SpecialFolders() { }

        /// <summary>
        /// Gets the path to the <see cref="global::System.Environment.SpecialFolder.Desktop"/> directory.
        /// </summary>
        public string DesktopPath => field ??= global::System.Environment.GetFolderPath(global::System.Environment.SpecialFolder.Desktop, global::LaquaiLib.Extensions.EnvironmentExtensions.get_DefaultSpecialFolderOption());
        /// <summary>
        /// Gets a <see cref="global::System.IO.DirectoryInfo"/> instance for the path returned by <see cref="DesktopPath"/>.
        /// </summary>
        public global::System.IO.DirectoryInfo Desktop => field ??= new global::System.IO.DirectoryInfo(DesktopPath);

        /// <summary>
        /// Gets the path to the <see cref="global::System.Environment.SpecialFolder.Programs"/> directory.
        /// </summary>
        public string ProgramsPath => field ??= global::System.Environment.GetFolderPath(global::System.Environment.SpecialFolder.Programs, global::LaquaiLib.Extensions.EnvironmentExtensions.get_DefaultSpecialFolderOption());
        /// <summary>
        /// Gets a <see cref="global::System.IO.DirectoryInfo"/> instance for the path returned by <see cref="ProgramsPath"/>.
        /// </summary>
        public global::System.IO.DirectoryInfo Programs => field ??= new global::System.IO.DirectoryInfo(ProgramsPath);

        /// <summary>
        /// Gets the path to the <see cref="global::System.Environment.SpecialFolder.MyDocuments"/> directory.
        /// </summary>
        public string MyDocumentsPath => field ??= global::System.Environment.GetFolderPath(global::System.Environment.SpecialFolder.MyDocuments, global::LaquaiLib.Extensions.EnvironmentExtensions.get_DefaultSpecialFolderOption());
        /// <summary>
        /// Gets a <see cref="global::System.IO.DirectoryInfo"/> instance for the path returned by <see cref="MyDocumentsPath"/>.
        /// </summary>
        public global::System.IO.DirectoryInfo MyDocuments => field ??= new global::System.IO.DirectoryInfo(MyDocumentsPath);

        /// <summary>
        /// Gets the path to the <see cref="global::System.Environment.SpecialFolder.Favorites"/> directory.
        /// </summary>
        public string FavoritesPath => field ??= global::System.Environment.GetFolderPath(global::System.Environment.SpecialFolder.Favorites, global::LaquaiLib.Extensions.EnvironmentExtensions.get_DefaultSpecialFolderOption());
        /// <summary>
        /// Gets a <see cref="global::System.IO.DirectoryInfo"/> instance for the path returned by <see cref="FavoritesPath"/>.
        /// </summary>
        public global::System.IO.DirectoryInfo Favorites => field ??= new global::System.IO.DirectoryInfo(FavoritesPath);

        /// <summary>
        /// Gets the path to the <see cref="global::System.Environment.SpecialFolder.Startup"/> directory.
        /// </summary>
        public string StartupPath => field ??= global::System.Environment.GetFolderPath(global::System.Environment.SpecialFolder.Startup, global::LaquaiLib.Extensions.EnvironmentExtensions.get_DefaultSpecialFolderOption());
        /// <summary>
        /// Gets a <see cref="global::System.IO.DirectoryInfo"/> instance for the path returned by <see cref="StartupPath"/>.
        /// </summary>
        public global::System.IO.DirectoryInfo Startup => field ??= new global::System.IO.DirectoryInfo(StartupPath);

        /// <summary>
        /// Gets the path to the <see cref="global::System.Environment.SpecialFolder.Recent"/> directory.
        /// </summary>
        public string RecentPath => field ??= global::System.Environment.GetFolderPath(global::System.Environment.SpecialFolder.Recent, global::LaquaiLib.Extensions.EnvironmentExtensions.get_DefaultSpecialFolderOption());
        /// <summary>
        /// Gets a <see cref="global::System.IO.DirectoryInfo"/> instance for the path returned by <see cref="RecentPath"/>.
        /// </summary>
        public global::System.IO.DirectoryInfo Recent => field ??= new global::System.IO.DirectoryInfo(RecentPath);

        /// <summary>
        /// Gets the path to the <see cref="global::System.Environment.SpecialFolder.SendTo"/> directory.
        /// </summary>
        public string SendToPath => field ??= global::System.Environment.GetFolderPath(global::System.Environment.SpecialFolder.SendTo, global::LaquaiLib.Extensions.EnvironmentExtensions.get_DefaultSpecialFolderOption());
        /// <summary>
        /// Gets a <see cref="global::System.IO.DirectoryInfo"/> instance for the path returned by <see cref="SendToPath"/>.
        /// </summary>
        public global::System.IO.DirectoryInfo SendTo => field ??= new global::System.IO.DirectoryInfo(SendToPath);

        /// <summary>
        /// Gets the path to the <see cref="global::System.Environment.SpecialFolder.StartMenu"/> directory.
        /// </summary>
        public string StartMenuPath => field ??= global::System.Environment.GetFolderPath(global::System.Environment.SpecialFolder.StartMenu, global::LaquaiLib.Extensions.EnvironmentExtensions.get_DefaultSpecialFolderOption());
        /// <summary>
        /// Gets a <see cref="global::System.IO.DirectoryInfo"/> instance for the path returned by <see cref="StartMenuPath"/>.
        /// </summary>
        public global::System.IO.DirectoryInfo StartMenu => field ??= new global::System.IO.DirectoryInfo(StartMenuPath);

        /// <summary>
        /// Gets the path to the <see cref="global::System.Environment.SpecialFolder.MyMusic"/> directory.
        /// </summary>
        public string MyMusicPath => field ??= global::System.Environment.GetFolderPath(global::System.Environment.SpecialFolder.MyMusic, global::LaquaiLib.Extensions.EnvironmentExtensions.get_DefaultSpecialFolderOption());
        /// <summary>
        /// Gets a <see cref="global::System.IO.DirectoryInfo"/> instance for the path returned by <see cref="MyMusicPath"/>.
        /// </summary>
        public global::System.IO.DirectoryInfo MyMusic => field ??= new global::System.IO.DirectoryInfo(MyMusicPath);

        /// <summary>
        /// Gets the path to the <see cref="global::System.Environment.SpecialFolder.MyVideos"/> directory.
        /// </summary>
        public string MyVideosPath => field ??= global::System.Environment.GetFolderPath(global::System.Environment.SpecialFolder.MyVideos, global::LaquaiLib.Extensions.EnvironmentExtensions.get_DefaultSpecialFolderOption());
        /// <summary>
        /// Gets a <see cref="global::System.IO.DirectoryInfo"/> instance for the path returned by <see cref="MyVideosPath"/>.
        /// </summary>
        public global::System.IO.DirectoryInfo MyVideos => field ??= new global::System.IO.DirectoryInfo(MyVideosPath);

        /// <summary>
        /// Gets the path to the <see cref="global::System.Environment.SpecialFolder.DesktopDirectory"/> directory.
        /// </summary>
        public string DesktopDirectoryPath => field ??= global::System.Environment.GetFolderPath(global::System.Environment.SpecialFolder.DesktopDirectory, global::LaquaiLib.Extensions.EnvironmentExtensions.get_DefaultSpecialFolderOption());
        /// <summary>
        /// Gets a <see cref="global::System.IO.DirectoryInfo"/> instance for the path returned by <see cref="DesktopDirectoryPath"/>.
        /// </summary>
        public global::System.IO.DirectoryInfo DesktopDirectory => field ??= new global::System.IO.DirectoryInfo(DesktopDirectoryPath);

        /// <summary>
        /// Gets the path to the <see cref="global::System.Environment.SpecialFolder.MyComputer"/> directory.
        /// </summary>
        public string MyComputerPath => field ??= global::System.Environment.GetFolderPath(global::System.Environment.SpecialFolder.MyComputer, global::LaquaiLib.Extensions.EnvironmentExtensions.get_DefaultSpecialFolderOption());
        /// <summary>
        /// Gets a <see cref="global::System.IO.DirectoryInfo"/> instance for the path returned by <see cref="MyComputerPath"/>.
        /// </summary>
        public global::System.IO.DirectoryInfo MyComputer => field ??= new global::System.IO.DirectoryInfo(MyComputerPath);

        /// <summary>
        /// Gets the path to the <see cref="global::System.Environment.SpecialFolder.NetworkShortcuts"/> directory.
        /// </summary>
        public string NetworkShortcutsPath => field ??= global::System.Environment.GetFolderPath(global::System.Environment.SpecialFolder.NetworkShortcuts, global::LaquaiLib.Extensions.EnvironmentExtensions.get_DefaultSpecialFolderOption());
        /// <summary>
        /// Gets a <see cref="global::System.IO.DirectoryInfo"/> instance for the path returned by <see cref="NetworkShortcutsPath"/>.
        /// </summary>
        public global::System.IO.DirectoryInfo NetworkShortcuts => field ??= new global::System.IO.DirectoryInfo(NetworkShortcutsPath);

        /// <summary>
        /// Gets the path to the <see cref="global::System.Environment.SpecialFolder.Fonts"/> directory.
        /// </summary>
        public string FontsPath => field ??= global::System.Environment.GetFolderPath(global::System.Environment.SpecialFolder.Fonts, global::LaquaiLib.Extensions.EnvironmentExtensions.get_DefaultSpecialFolderOption());
        /// <summary>
        /// Gets a <see cref="global::System.IO.DirectoryInfo"/> instance for the path returned by <see cref="FontsPath"/>.
        /// </summary>
        public global::System.IO.DirectoryInfo Fonts => field ??= new global::System.IO.DirectoryInfo(FontsPath);

        /// <summary>
        /// Gets the path to the <see cref="global::System.Environment.SpecialFolder.Templates"/> directory.
        /// </summary>
        public string TemplatesPath => field ??= global::System.Environment.GetFolderPath(global::System.Environment.SpecialFolder.Templates, global::LaquaiLib.Extensions.EnvironmentExtensions.get_DefaultSpecialFolderOption());
        /// <summary>
        /// Gets a <see cref="global::System.IO.DirectoryInfo"/> instance for the path returned by <see cref="TemplatesPath"/>.
        /// </summary>
        public global::System.IO.DirectoryInfo Templates => field ??= new global::System.IO.DirectoryInfo(TemplatesPath);

        /// <summary>
        /// Gets the path to the <see cref="global::System.Environment.SpecialFolder.CommonStartMenu"/> directory.
        /// </summary>
        public string CommonStartMenuPath => field ??= global::System.Environment.GetFolderPath(global::System.Environment.SpecialFolder.CommonStartMenu, global::LaquaiLib.Extensions.EnvironmentExtensions.get_DefaultSpecialFolderOption());
        /// <summary>
        /// Gets a <see cref="global::System.IO.DirectoryInfo"/> instance for the path returned by <see cref="CommonStartMenuPath"/>.
        /// </summary>
        public global::System.IO.DirectoryInfo CommonStartMenu => field ??= new global::System.IO.DirectoryInfo(CommonStartMenuPath);

        /// <summary>
        /// Gets the path to the <see cref="global::System.Environment.SpecialFolder.CommonPrograms"/> directory.
        /// </summary>
        public string CommonProgramsPath => field ??= global::System.Environment.GetFolderPath(global::System.Environment.SpecialFolder.CommonPrograms, global::LaquaiLib.Extensions.EnvironmentExtensions.get_DefaultSpecialFolderOption());
        /// <summary>
        /// Gets a <see cref="global::System.IO.DirectoryInfo"/> instance for the path returned by <see cref="CommonProgramsPath"/>.
        /// </summary>
        public global::System.IO.DirectoryInfo CommonPrograms => field ??= new global::System.IO.DirectoryInfo(CommonProgramsPath);

        /// <summary>
        /// Gets the path to the <see cref="global::System.Environment.SpecialFolder.CommonStartup"/> directory.
        /// </summary>
        public string CommonStartupPath => field ??= global::System.Environment.GetFolderPath(global::System.Environment.SpecialFolder.CommonStartup, global::LaquaiLib.Extensions.EnvironmentExtensions.get_DefaultSpecialFolderOption());
        /// <summary>
        /// Gets a <see cref="global::System.IO.DirectoryInfo"/> instance for the path returned by <see cref="CommonStartupPath"/>.
        /// </summary>
        public global::System.IO.DirectoryInfo CommonStartup => field ??= new global::System.IO.DirectoryInfo(CommonStartupPath);

        /// <summary>
        /// Gets the path to the <see cref="global::System.Environment.SpecialFolder.CommonDesktopDirectory"/> directory.
        /// </summary>
        public string CommonDesktopDirectoryPath => field ??= global::System.Environment.GetFolderPath(global::System.Environment.SpecialFolder.CommonDesktopDirectory, global::LaquaiLib.Extensions.EnvironmentExtensions.get_DefaultSpecialFolderOption());
        /// <summary>
        /// Gets a <see cref="global::System.IO.DirectoryInfo"/> instance for the path returned by <see cref="CommonDesktopDirectoryPath"/>.
        /// </summary>
        public global::System.IO.DirectoryInfo CommonDesktopDirectory => field ??= new global::System.IO.DirectoryInfo(CommonDesktopDirectoryPath);

        /// <summary>
        /// Gets the path to the <see cref="global::System.Environment.SpecialFolder.ApplicationData"/> directory.
        /// </summary>
        public string ApplicationDataPath => field ??= global::System.Environment.GetFolderPath(global::System.Environment.SpecialFolder.ApplicationData, global::LaquaiLib.Extensions.EnvironmentExtensions.get_DefaultSpecialFolderOption());
        /// <summary>
        /// Gets a <see cref="global::System.IO.DirectoryInfo"/> instance for the path returned by <see cref="ApplicationDataPath"/>.
        /// </summary>
        public global::System.IO.DirectoryInfo ApplicationData => field ??= new global::System.IO.DirectoryInfo(ApplicationDataPath);

        /// <summary>
        /// Gets the path to the <see cref="global::System.Environment.SpecialFolder.PrinterShortcuts"/> directory.
        /// </summary>
        public string PrinterShortcutsPath => field ??= global::System.Environment.GetFolderPath(global::System.Environment.SpecialFolder.PrinterShortcuts, global::LaquaiLib.Extensions.EnvironmentExtensions.get_DefaultSpecialFolderOption());
        /// <summary>
        /// Gets a <see cref="global::System.IO.DirectoryInfo"/> instance for the path returned by <see cref="PrinterShortcutsPath"/>.
        /// </summary>
        public global::System.IO.DirectoryInfo PrinterShortcuts => field ??= new global::System.IO.DirectoryInfo(PrinterShortcutsPath);

        /// <summary>
        /// Gets the path to the <see cref="global::System.Environment.SpecialFolder.LocalApplicationData"/> directory.
        /// </summary>
        public string LocalApplicationDataPath => field ??= global::System.Environment.GetFolderPath(global::System.Environment.SpecialFolder.LocalApplicationData, global::LaquaiLib.Extensions.EnvironmentExtensions.get_DefaultSpecialFolderOption());
        /// <summary>
        /// Gets a <see cref="global::System.IO.DirectoryInfo"/> instance for the path returned by <see cref="LocalApplicationDataPath"/>.
        /// </summary>
        public global::System.IO.DirectoryInfo LocalApplicationData => field ??= new global::System.IO.DirectoryInfo(LocalApplicationDataPath);

        /// <summary>
        /// Gets the path to the <see cref="global::System.Environment.SpecialFolder.InternetCache"/> directory.
        /// </summary>
        public string InternetCachePath => field ??= global::System.Environment.GetFolderPath(global::System.Environment.SpecialFolder.InternetCache, global::LaquaiLib.Extensions.EnvironmentExtensions.get_DefaultSpecialFolderOption());
        /// <summary>
        /// Gets a <see cref="global::System.IO.DirectoryInfo"/> instance for the path returned by <see cref="InternetCachePath"/>.
        /// </summary>
        public global::System.IO.DirectoryInfo InternetCache => field ??= new global::System.IO.DirectoryInfo(InternetCachePath);

        /// <summary>
        /// Gets the path to the <see cref="global::System.Environment.SpecialFolder.Cookies"/> directory.
        /// </summary>
        public string CookiesPath => field ??= global::System.Environment.GetFolderPath(global::System.Environment.SpecialFolder.Cookies, global::LaquaiLib.Extensions.EnvironmentExtensions.get_DefaultSpecialFolderOption());
        /// <summary>
        /// Gets a <see cref="global::System.IO.DirectoryInfo"/> instance for the path returned by <see cref="CookiesPath"/>.
        /// </summary>
        public global::System.IO.DirectoryInfo Cookies => field ??= new global::System.IO.DirectoryInfo(CookiesPath);

        /// <summary>
        /// Gets the path to the <see cref="global::System.Environment.SpecialFolder.History"/> directory.
        /// </summary>
        public string HistoryPath => field ??= global::System.Environment.GetFolderPath(global::System.Environment.SpecialFolder.History, global::LaquaiLib.Extensions.EnvironmentExtensions.get_DefaultSpecialFolderOption());
        /// <summary>
        /// Gets a <see cref="global::System.IO.DirectoryInfo"/> instance for the path returned by <see cref="HistoryPath"/>.
        /// </summary>
        public global::System.IO.DirectoryInfo History => field ??= new global::System.IO.DirectoryInfo(HistoryPath);

        /// <summary>
        /// Gets the path to the <see cref="global::System.Environment.SpecialFolder.CommonApplicationData"/> directory.
        /// </summary>
        public string CommonApplicationDataPath => field ??= global::System.Environment.GetFolderPath(global::System.Environment.SpecialFolder.CommonApplicationData, global::LaquaiLib.Extensions.EnvironmentExtensions.get_DefaultSpecialFolderOption());
        /// <summary>
        /// Gets a <see cref="global::System.IO.DirectoryInfo"/> instance for the path returned by <see cref="CommonApplicationDataPath"/>.
        /// </summary>
        public global::System.IO.DirectoryInfo CommonApplicationData => field ??= new global::System.IO.DirectoryInfo(CommonApplicationDataPath);

        /// <summary>
        /// Gets the path to the <see cref="global::System.Environment.SpecialFolder.Windows"/> directory.
        /// </summary>
        public string WindowsPath => field ??= global::System.Environment.GetFolderPath(global::System.Environment.SpecialFolder.Windows, global::LaquaiLib.Extensions.EnvironmentExtensions.get_DefaultSpecialFolderOption());
        /// <summary>
        /// Gets a <see cref="global::System.IO.DirectoryInfo"/> instance for the path returned by <see cref="WindowsPath"/>.
        /// </summary>
        public global::System.IO.DirectoryInfo Windows => field ??= new global::System.IO.DirectoryInfo(WindowsPath);

        /// <summary>
        /// Gets the path to the <see cref="global::System.Environment.SpecialFolder.System"/> directory.
        /// </summary>
        public string SystemPath => field ??= global::System.Environment.GetFolderPath(global::System.Environment.SpecialFolder.System, global::LaquaiLib.Extensions.EnvironmentExtensions.get_DefaultSpecialFolderOption());
        /// <summary>
        /// Gets a <see cref="global::System.IO.DirectoryInfo"/> instance for the path returned by <see cref="SystemPath"/>.
        /// </summary>
        public global::System.IO.DirectoryInfo System => field ??= new global::System.IO.DirectoryInfo(SystemPath);

        /// <summary>
        /// Gets the path to the <see cref="global::System.Environment.SpecialFolder.ProgramFiles"/> directory.
        /// </summary>
        public string ProgramFilesPath => field ??= global::System.Environment.GetFolderPath(global::System.Environment.SpecialFolder.ProgramFiles, global::LaquaiLib.Extensions.EnvironmentExtensions.get_DefaultSpecialFolderOption());
        /// <summary>
        /// Gets a <see cref="global::System.IO.DirectoryInfo"/> instance for the path returned by <see cref="ProgramFilesPath"/>.
        /// </summary>
        public global::System.IO.DirectoryInfo ProgramFiles => field ??= new global::System.IO.DirectoryInfo(ProgramFilesPath);

        /// <summary>
        /// Gets the path to the <see cref="global::System.Environment.SpecialFolder.MyPictures"/> directory.
        /// </summary>
        public string MyPicturesPath => field ??= global::System.Environment.GetFolderPath(global::System.Environment.SpecialFolder.MyPictures, global::LaquaiLib.Extensions.EnvironmentExtensions.get_DefaultSpecialFolderOption());
        /// <summary>
        /// Gets a <see cref="global::System.IO.DirectoryInfo"/> instance for the path returned by <see cref="MyPicturesPath"/>.
        /// </summary>
        public global::System.IO.DirectoryInfo MyPictures => field ??= new global::System.IO.DirectoryInfo(MyPicturesPath);

        /// <summary>
        /// Gets the path to the <see cref="global::System.Environment.SpecialFolder.UserProfile"/> directory.
        /// </summary>
        public string UserProfilePath => field ??= global::System.Environment.GetFolderPath(global::System.Environment.SpecialFolder.UserProfile, global::LaquaiLib.Extensions.EnvironmentExtensions.get_DefaultSpecialFolderOption());
        /// <summary>
        /// Gets a <see cref="global::System.IO.DirectoryInfo"/> instance for the path returned by <see cref="UserProfilePath"/>.
        /// </summary>
        public global::System.IO.DirectoryInfo UserProfile => field ??= new global::System.IO.DirectoryInfo(UserProfilePath);

        /// <summary>
        /// Gets the path to the <see cref="global::System.Environment.SpecialFolder.SystemX86"/> directory.
        /// </summary>
        public string SystemX86Path => field ??= global::System.Environment.GetFolderPath(global::System.Environment.SpecialFolder.SystemX86, global::LaquaiLib.Extensions.EnvironmentExtensions.get_DefaultSpecialFolderOption());
        /// <summary>
        /// Gets a <see cref="global::System.IO.DirectoryInfo"/> instance for the path returned by <see cref="SystemX86Path"/>.
        /// </summary>
        public global::System.IO.DirectoryInfo SystemX86 => field ??= new global::System.IO.DirectoryInfo(SystemX86Path);

        /// <summary>
        /// Gets the path to the <see cref="global::System.Environment.SpecialFolder.ProgramFilesX86"/> directory.
        /// </summary>
        public string ProgramFilesX86Path => field ??= global::System.Environment.GetFolderPath(global::System.Environment.SpecialFolder.ProgramFilesX86, global::LaquaiLib.Extensions.EnvironmentExtensions.get_DefaultSpecialFolderOption());
        /// <summary>
        /// Gets a <see cref="global::System.IO.DirectoryInfo"/> instance for the path returned by <see cref="ProgramFilesX86Path"/>.
        /// </summary>
        public global::System.IO.DirectoryInfo ProgramFilesX86 => field ??= new global::System.IO.DirectoryInfo(ProgramFilesX86Path);

        /// <summary>
        /// Gets the path to the <see cref="global::System.Environment.SpecialFolder.CommonProgramFiles"/> directory.
        /// </summary>
        public string CommonProgramFilesPath => field ??= global::System.Environment.GetFolderPath(global::System.Environment.SpecialFolder.CommonProgramFiles, global::LaquaiLib.Extensions.EnvironmentExtensions.get_DefaultSpecialFolderOption());
        /// <summary>
        /// Gets a <see cref="global::System.IO.DirectoryInfo"/> instance for the path returned by <see cref="CommonProgramFilesPath"/>.
        /// </summary>
        public global::System.IO.DirectoryInfo CommonProgramFiles => field ??= new global::System.IO.DirectoryInfo(CommonProgramFilesPath);

        /// <summary>
        /// Gets the path to the <see cref="global::System.Environment.SpecialFolder.CommonProgramFilesX86"/> directory.
        /// </summary>
        public string CommonProgramFilesX86Path => field ??= global::System.Environment.GetFolderPath(global::System.Environment.SpecialFolder.CommonProgramFilesX86, global::LaquaiLib.Extensions.EnvironmentExtensions.get_DefaultSpecialFolderOption());
        /// <summary>
        /// Gets a <see cref="global::System.IO.DirectoryInfo"/> instance for the path returned by <see cref="CommonProgramFilesX86Path"/>.
        /// </summary>
        public global::System.IO.DirectoryInfo CommonProgramFilesX86 => field ??= new global::System.IO.DirectoryInfo(CommonProgramFilesX86Path);

        /// <summary>
        /// Gets the path to the <see cref="global::System.Environment.SpecialFolder.CommonTemplates"/> directory.
        /// </summary>
        public string CommonTemplatesPath => field ??= global::System.Environment.GetFolderPath(global::System.Environment.SpecialFolder.CommonTemplates, global::LaquaiLib.Extensions.EnvironmentExtensions.get_DefaultSpecialFolderOption());
        /// <summary>
        /// Gets a <see cref="global::System.IO.DirectoryInfo"/> instance for the path returned by <see cref="CommonTemplatesPath"/>.
        /// </summary>
        public global::System.IO.DirectoryInfo CommonTemplates => field ??= new global::System.IO.DirectoryInfo(CommonTemplatesPath);

        /// <summary>
        /// Gets the path to the <see cref="global::System.Environment.SpecialFolder.CommonDocuments"/> directory.
        /// </summary>
        public string CommonDocumentsPath => field ??= global::System.Environment.GetFolderPath(global::System.Environment.SpecialFolder.CommonDocuments, global::LaquaiLib.Extensions.EnvironmentExtensions.get_DefaultSpecialFolderOption());
        /// <summary>
        /// Gets a <see cref="global::System.IO.DirectoryInfo"/> instance for the path returned by <see cref="CommonDocumentsPath"/>.
        /// </summary>
        public global::System.IO.DirectoryInfo CommonDocuments => field ??= new global::System.IO.DirectoryInfo(CommonDocumentsPath);

        /// <summary>
        /// Gets the path to the <see cref="global::System.Environment.SpecialFolder.CommonAdminTools"/> directory.
        /// </summary>
        public string CommonAdminToolsPath => field ??= global::System.Environment.GetFolderPath(global::System.Environment.SpecialFolder.CommonAdminTools, global::LaquaiLib.Extensions.EnvironmentExtensions.get_DefaultSpecialFolderOption());
        /// <summary>
        /// Gets a <see cref="global::System.IO.DirectoryInfo"/> instance for the path returned by <see cref="CommonAdminToolsPath"/>.
        /// </summary>
        public global::System.IO.DirectoryInfo CommonAdminTools => field ??= new global::System.IO.DirectoryInfo(CommonAdminToolsPath);

        /// <summary>
        /// Gets the path to the <see cref="global::System.Environment.SpecialFolder.AdminTools"/> directory.
        /// </summary>
        public string AdminToolsPath => field ??= global::System.Environment.GetFolderPath(global::System.Environment.SpecialFolder.AdminTools, global::LaquaiLib.Extensions.EnvironmentExtensions.get_DefaultSpecialFolderOption());
        /// <summary>
        /// Gets a <see cref="global::System.IO.DirectoryInfo"/> instance for the path returned by <see cref="AdminToolsPath"/>.
        /// </summary>
        public global::System.IO.DirectoryInfo AdminTools => field ??= new global::System.IO.DirectoryInfo(AdminToolsPath);

        /// <summary>
        /// Gets the path to the <see cref="global::System.Environment.SpecialFolder.CommonMusic"/> directory.
        /// </summary>
        public string CommonMusicPath => field ??= global::System.Environment.GetFolderPath(global::System.Environment.SpecialFolder.CommonMusic, global::LaquaiLib.Extensions.EnvironmentExtensions.get_DefaultSpecialFolderOption());
        /// <summary>
        /// Gets a <see cref="global::System.IO.DirectoryInfo"/> instance for the path returned by <see cref="CommonMusicPath"/>.
        /// </summary>
        public global::System.IO.DirectoryInfo CommonMusic => field ??= new global::System.IO.DirectoryInfo(CommonMusicPath);

        /// <summary>
        /// Gets the path to the <see cref="global::System.Environment.SpecialFolder.CommonPictures"/> directory.
        /// </summary>
        public string CommonPicturesPath => field ??= global::System.Environment.GetFolderPath(global::System.Environment.SpecialFolder.CommonPictures, global::LaquaiLib.Extensions.EnvironmentExtensions.get_DefaultSpecialFolderOption());
        /// <summary>
        /// Gets a <see cref="global::System.IO.DirectoryInfo"/> instance for the path returned by <see cref="CommonPicturesPath"/>.
        /// </summary>
        public global::System.IO.DirectoryInfo CommonPictures => field ??= new global::System.IO.DirectoryInfo(CommonPicturesPath);

        /// <summary>
        /// Gets the path to the <see cref="global::System.Environment.SpecialFolder.CommonVideos"/> directory.
        /// </summary>
        public string CommonVideosPath => field ??= global::System.Environment.GetFolderPath(global::System.Environment.SpecialFolder.CommonVideos, global::LaquaiLib.Extensions.EnvironmentExtensions.get_DefaultSpecialFolderOption());
        /// <summary>
        /// Gets a <see cref="global::System.IO.DirectoryInfo"/> instance for the path returned by <see cref="CommonVideosPath"/>.
        /// </summary>
        public global::System.IO.DirectoryInfo CommonVideos => field ??= new global::System.IO.DirectoryInfo(CommonVideosPath);

        /// <summary>
        /// Gets the path to the <see cref="global::System.Environment.SpecialFolder.Resources"/> directory.
        /// </summary>
        public string ResourcesPath => field ??= global::System.Environment.GetFolderPath(global::System.Environment.SpecialFolder.Resources, global::LaquaiLib.Extensions.EnvironmentExtensions.get_DefaultSpecialFolderOption());
        /// <summary>
        /// Gets a <see cref="global::System.IO.DirectoryInfo"/> instance for the path returned by <see cref="ResourcesPath"/>.
        /// </summary>
        public global::System.IO.DirectoryInfo Resources => field ??= new global::System.IO.DirectoryInfo(ResourcesPath);

        /// <summary>
        /// Gets the path to the <see cref="global::System.Environment.SpecialFolder.LocalizedResources"/> directory.
        /// </summary>
        public string LocalizedResourcesPath => field ??= global::System.Environment.GetFolderPath(global::System.Environment.SpecialFolder.LocalizedResources, global::LaquaiLib.Extensions.EnvironmentExtensions.get_DefaultSpecialFolderOption());
        /// <summary>
        /// Gets a <see cref="global::System.IO.DirectoryInfo"/> instance for the path returned by <see cref="LocalizedResourcesPath"/>.
        /// </summary>
        public global::System.IO.DirectoryInfo LocalizedResources => field ??= new global::System.IO.DirectoryInfo(LocalizedResourcesPath);

        /// <summary>
        /// Gets the path to the <see cref="global::System.Environment.SpecialFolder.CommonOemLinks"/> directory.
        /// </summary>
        public string CommonOemLinksPath => field ??= global::System.Environment.GetFolderPath(global::System.Environment.SpecialFolder.CommonOemLinks, global::LaquaiLib.Extensions.EnvironmentExtensions.get_DefaultSpecialFolderOption());
        /// <summary>
        /// Gets a <see cref="global::System.IO.DirectoryInfo"/> instance for the path returned by <see cref="CommonOemLinksPath"/>.
        /// </summary>
        public global::System.IO.DirectoryInfo CommonOemLinks => field ??= new global::System.IO.DirectoryInfo(CommonOemLinksPath);

        /// <summary>
        /// Gets the path to the <see cref="global::System.Environment.SpecialFolder.CDBurning"/> directory.
        /// </summary>
        public string CDBurningPath => field ??= global::System.Environment.GetFolderPath(global::System.Environment.SpecialFolder.CDBurning, global::LaquaiLib.Extensions.EnvironmentExtensions.get_DefaultSpecialFolderOption());
        /// <summary>
        /// Gets a <see cref="global::System.IO.DirectoryInfo"/> instance for the path returned by <see cref="CDBurningPath"/>.
        /// </summary>
        public global::System.IO.DirectoryInfo CDBurning => field ??= new global::System.IO.DirectoryInfo(CDBurningPath);

    }
}
