$ErrorActionPreference = 'Stop'
$L = [System.Collections.Generic.List[string]]::new()
$indent = 0
$indentStr = '    '
function W([string]$s = '') {
    if ($s -eq '') {
        $L.Add('')
    }
    else {
        $L.Add($indentStr * $indent + $s)
    }
}


W '// Generated by gen-Environment.SpecialFolders.ps1 in this directory, edit that script and re-run it, not this file'
W ''

W @'
namespace LaquaiLib.Extensions
{
    public static class EnvironmentExtensions
    {
        internal static global::System.Environment.SpecialFolderOption _sfo;
        extension(Environment)
        {
            /// <summary>
            /// Gets or sets the default <see cref="global::System.Environment.SpecialFolderOption"/> value that <see cref="global::LaquaiLib.Bcl.System.SpecialFolders"/> uses to retrieve paths.
            /// </summary>
            public static global::System.Environment.SpecialFolderOption DefaultSpecialFolderOption
            {
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                get => _sfo;
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                set => _sfo = value;
            }
            public static global::LaquaiLib.Bcl.System.SpecialFolders SpecialFolders => global::LaquaiLib.Bcl.System.SpecialFolders.Instance;
        }
    }
}

namespace LaquaiLib.Bcl.System
{
    /// <summary>
    /// Provides access to the special folders of the system.
    /// </summary>
    public class SpecialFolders
    {
        public static readonly SpecialFolders Instance = new SpecialFolders();
        private SpecialFolders() { }

'@

$indent = 2

$vals = [System.Enum]::GetValues([System.Environment+SpecialFolder])
$vals = [System.Collections.Generic.List[System.Environment+SpecialFolder]]::new([System.Collections.Generic.HashSet[System.Environment+SpecialFolder]]::new($vals))
$vals.Sort()

foreach ($val in $vals) {
    $name = [System.Enum]::GetName([System.Environment+SpecialFolder], $val)
    $namePath = $name + 'Path'

    W '/// <summary>'
    W "/// Gets the path to the <see cref=`"global::System.Environment.SpecialFolder.$name`"/> directory."
    W '/// </summary>'
    W "public string $namePath => field ??= global::System.Environment.GetFolderPath(global::System.Environment.SpecialFolder.$name, global::LaquaiLib.Extensions.EnvironmentExtensions.get_DefaultSpecialFolderOption());"
    W '/// <summary>'
    W "/// Gets a <see cref=`"global::System.IO.DirectoryInfo`"/> instance for the path returned by <see cref=`"$namePath`"/>."
    W '/// </summary>'
    W "public global::System.IO.DirectoryInfo $name => field ??= new global::System.IO.DirectoryInfo($namePath);"
    W ''
}

$indent--
W '}'
$indent--
W '}'


$text = ($L -join [System.Environment]::NewLine) + [System.Environment]::NewLine
$enc = [System.Text.UTF8Encoding]::new($true)
$out = Join-Path $PSScriptRoot 'Environment.SpecialFolders.cs'
[System.IO.File]::WriteAllText($out, $text, $enc)
Write-Output "wrote $($text.Split([System.Environment]::NewLine).Length) lines to $out"
