<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <None Remove="bin\Debug\netstandard2.0\\LaquaiLib.Analyzers.Fixes.dll" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.Common" Version="5.9.0" PrivateAssets="all" />
    <PackageReference Update="Microsoft.CodeAnalysis.CSharp" Version="5.9.0" />
    <ProjectReference Include="..\LaquaiLib.Analyzers.Shared\LaquaiLib.Analyzers.Shared.csproj" />

    <Using Include="System.Composition" />
    <Using Include="Microsoft.CodeAnalysis.CodeActions" />
    <Using Include="Microsoft.CodeAnalysis.CodeFixes" />
    <Using Include="Microsoft.CodeAnalysis.Simplification" />
    <Using Include="Microsoft.CodeAnalysis.Formatting" />
    <Using Include="Microsoft.CodeAnalysis.CodeRefactorings" />
    <Using Include="Microsoft.CodeAnalysis.Operations" />
    <Using Include="Microsoft.CodeAnalysis.Editing" />

    <Using Include="LaquaiLib.Analyzers.Shared" />
  </ItemGroup>

</Project>