namespace LaquaiLib.Generators;
internal static class Constants
{
    public const string GeneratedFileHeader = """
        // <auto-generated />
        // This file was generated by LaquaiLib.Generators. Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
        """;

    public const string UnsafeAccessor_Method = "[System.Runtime.CompilerServices.UnsafeAccessor(System.Runtime.CompilerServices.UnsafeAccessorKind.Method)]";
    public const string UnsafeAccessor_Field = "[System.Runtime.CompilerServices.UnsafeAccessor(System.Runtime.CompilerServices.UnsafeAccessorKind.Field)]";
    public const string UnsafeAccessor_Ctor = "[System.Runtime.CompilerServices.UnsafeAccessor(System.Runtime.CompilerServices.UnsafeAccessorKind.Constructor)]";
    public const string MethodImpl_AggressiveInlining = "[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]";
}

internal static class FormatStrings
{
}