using System.Reflection;

using LaquaiLib.Analyzers.Shared;

namespace LaquaiLib.Generators;
internal static class Constants
{
    private static readonly Assembly _ownAsm = typeof(Constants).Assembly;
    private static readonly AssemblyName _ownAsmName = _ownAsm.GetName();

    public const string GeneratedFileHeader = """
        // <auto-generated />
        // This file was generated by LaquaiLib.Generators. Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
        """;

    public const string UnsafeAccessor_Method = "[System.Runtime.CompilerServices.UnsafeAccessor(System.Runtime.CompilerServices.UnsafeAccessorKind.Method)]";
    public const string UnsafeAccessor_Field = "[System.Runtime.CompilerServices.UnsafeAccessor(System.Runtime.CompilerServices.UnsafeAccessorKind.Field)]";
    public const string UnsafeAccessor_Ctor = "[System.Runtime.CompilerServices.UnsafeAccessor(System.Runtime.CompilerServices.UnsafeAccessorKind.Constructor)]";
    public const string MethodImpl_AggressiveInlining = "[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]";

    public static string GeneratedCodeAttribute(Type type) => $"""
        [global::System.CodeDom.Compiler.GeneratedCode("{type.GetFriendlyName()}", "{_ownAsmName.Version}")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        """;
}

internal static class FormatStrings
{
}