using System.Reflection;

using LaquaiLib.Analyzers.Shared;

namespace LaquaiLib.Generators;

#pragma warning disable IDE0058 // Expression value is never used

internal static class SourceEmitHelper
{
    private static readonly Assembly _ownAsm = typeof(SourceEmitHelper).Assembly;
    private static readonly AssemblyName _ownAsmName = _ownAsm.GetName();

    public const string GeneratedFileHeader = """
        // <auto-generated />
        // This file was generated by LaquaiLib.Generators. Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

        """;

    public const string UnsafeAccessor_Method = "[System.Runtime.CompilerServices.UnsafeAccessor(System.Runtime.CompilerServices.UnsafeAccessorKind.Method)]";
    public const string UnsafeAccessor_Field = "[System.Runtime.CompilerServices.UnsafeAccessor(System.Runtime.CompilerServices.UnsafeAccessorKind.Field)]";
    public const string UnsafeAccessor_Ctor = "[System.Runtime.CompilerServices.UnsafeAccessor(System.Runtime.CompilerServices.UnsafeAccessorKind.Constructor)]";
    public const string MethodImpl_AggressiveInlining = "[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]";

    public static string GeneratedCodeAttribute(Type type) => $"""
        [global::System.CodeDom.Compiler.GeneratedCode("{type.GetFriendlyName()}", "{_ownAsmName.Version}")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        """;
    public static string Summary(string summary, string returnDesc = null, ReadOnlySpan<(string, string)> parameters = default, ReadOnlySpan<(string, string)> typeParameters = default, ReadOnlySpan<(string, string)> exceptions = default, ReadOnlySpan<string> remarksParas = default)
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// {summary}");
        sb.AppendLine("/// </summary>");

        if (typeParameters.Length > 0)
        {
            for (var i = 0; i < typeParameters.Length; i++)
            {
                var (name, desc) = typeParameters[i];
                if (string.IsNullOrEmpty(name) || string.IsNullOrEmpty(desc))
                {
                    continue;
                }
                sb.AppendLine($"/// <typeparam name=\"{name}\">{desc}</typeparam>");
            }
        }

        if (parameters.Length > 0)
        {
            for (var i = 0; i < parameters.Length; i++)
            {
                var (name, desc) = parameters[i];
                if (string.IsNullOrEmpty(name) || string.IsNullOrEmpty(desc))
                {
                    continue;
                }

                sb.AppendLine($"/// <param name=\"{name}\">{desc}</param>");
            }
        }

        if (!string.IsNullOrEmpty(returnDesc))
        {
            sb.AppendLine($"/// <returns>{returnDesc}</returns>");
        }

        if (exceptions.Length > 0)
        {
            for (var i = 0; i < exceptions.Length; i++)
            {
                var (name, desc) = exceptions[i];
                if (string.IsNullOrEmpty(name) || string.IsNullOrEmpty(desc))
                {
                    continue;
                }

                sb.AppendLine($"/// <exception cref=\"{name}\">{desc}</exception>");
            }
        }

        if (remarksParas.Length > 0)
        {
            sb.AppendLine("/// <remarks>");
            for (var i = 0; i < remarksParas.Length; i++)
            {
                var para = remarksParas[i];
                if (string.IsNullOrEmpty(para))
                {
                    continue;
                }

                if (i == 0)
                {
                    sb.AppendLine($"/// {para}");
                    continue;
                }
                sb.AppendLine($"/// <para/>{para}");
            }
            sb.AppendLine("/// </remarks>");
        }

        return sb.ToString();
    }
}

internal static class Delegates
{
    /// <summary>
    /// Returns <see langword="true"/> for any input <see cref="SyntaxNode"/>.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool NoFilterPredicate(SyntaxNode node, CancellationToken ct) => true;
    /// <summary>
    /// Returns <see langword="true"/> if the input <see cref="SyntaxNode"/> is of type <typeparamref name="T"/>.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool TypeCheckPredicate<T>(SyntaxNode node, CancellationToken ct) => node is T;

    /// <summary>
    /// Returns the input <see cref="GeneratorSyntaxContext.Node"/> retyped as <typeparamref name="T"/>.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static T CastSelector<T>(GeneratorSyntaxContext context, CancellationToken ct) where T : SyntaxNode => context.Node as T;
    /// <summary>
    /// Returns the input <see cref="GeneratorSyntaxContext.Node"/> retyped as <typeparamref name="T"/>, bypassing the cast type check.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static T UnsafeCastSelector<T>(GeneratorSyntaxContext context, CancellationToken ct) where T : SyntaxNode => Unsafe.As<T>(context.Node);
    /// <summary>
    /// Returns the input <see cref="GeneratorAttributeSyntaxContext.TargetNode"/> retyped as <typeparamref name="T"/>.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static T CastSelector<T>(GeneratorAttributeSyntaxContext context, CancellationToken ct) where T : SyntaxNode => context.TargetNode as T;
    /// <summary>
    /// Returns the input <see cref="GeneratorAttributeSyntaxContext.TargetNode"/> retyped as <typeparamref name="T"/>, bypassing the cast type check.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static T UnsafeCastSelector<T>(GeneratorAttributeSyntaxContext context, CancellationToken ct) where T : SyntaxNode => Unsafe.As<T>(context.TargetNode);
}