$ErrorActionPreference = 'Stop'
$L = [System.Collections.Generic.List[string]]::new()
function W([string]$s = '') { $L.Add($s) }

W '// Generated by gen-unions.ps1 in this directory - edit that script and re-run it, not this file'
W '// This file contains a series of type definitions readily usable using any type parameters'
W '// They store their values directly in typed fields; the only boxing is through the contract-mandated object Value property'
W ''
W 'using System.Diagnostics.CodeAnalysis;'
W ''
W 'namespace LaquaiLib.Wrappers;'
W ''
W '/// <summary>'
W '/// Provides shared members for the union types in this namespace.'
W '/// </summary>'
W 'public static class LaquaiLibUnion'
W '{'
W '    /// <summary>'
W '    /// The <see langword="string"/> representation of an empty union.'
W '    /// </summary>'
W '    public const string NoValue = "Empty";'
W '    // constrained callvirt, so no boxing for value types that override ToString'
W '    internal static string ToString<T>(in T value) => value is null ? NoValue : value.ToString() ?? NoValue;'
W '    [DoesNotReturn, MethodImpl(MethodImplOptions.NoInlining)]'
W '    internal static T ThrowNotHeld<T>() => throw new InvalidOperationException($"The union does not encapsulate a value of type ''{typeof(T)}''.");'
W '}'

# Result<T>
W '/// <summary>'
W '/// Represents a union that encapsulates a <typeparamref name="T"/> value or nothing at all.'
W '/// </summary>'
W '/// <typeparam name="T">The type of the value the union may encapsulate.</typeparam>'
W '[Union]'
W 'public readonly struct Result<T> : IEquatable<Result<T>>, IEquatable<T>'
W '{'
W '    private readonly T _v;'
W '    private readonly bool _hasValue;'
W ''
W '    /// <summary>'
W '    /// Initializes a new <see cref="Result{T}"/> encapsulating the specified value.'
W '    /// </summary>'
W '    /// <param name="value">The value to encapsulate.</param>'
W '    public Result(T value)'
W '    {'
W '        _v = value;'
W '        _hasValue = true;'
W '    }'
W ''
W '    /// <summary>'
W '    /// Gets the value encapsulated in the union or <see langword="null"/> if the union is empty. Boxing occurs for value type <typeparamref name="T"/>.'
W '    /// </summary>'
W '    public object Value => _hasValue ? _v : null;'
W '    /// <summary>'
W '    /// Gets whether the union encapsulates a non-<see langword="null"/> value.'
W '    /// </summary>'
W '    public bool HasValue => _hasValue && _v is not null;'
W ''
W '    /// <summary>'
W '    /// Returns the value the union was constructed with, which may be <see langword="null"/>, or throws if the union was not constructed with a value.'
W '    /// </summary>'
W '    /// <returns>The encapsulated <typeparamref name="T"/> value.</returns>'
W '    /// <exception cref="InvalidOperationException">Thrown if the union was not constructed with a value. A union constructed with <see langword="null"/> returns that <see langword="null"/> instead of throwing, even though <see cref="HasValue"/> is <see langword="false"/> for it.</exception>'
W '    [MethodImpl(MethodImplOptions.AggressiveInlining)]'
W '    public T AsValue() => _hasValue ? _v : LaquaiLibUnion.ThrowNotHeld<T>();'
W '    /// <summary>'
W '    /// Attempts to retrieve the value encapsulated in the union.'
W '    /// </summary>'
W '    /// <param name="value">An <see langword="out"/> variable that receives the encapsulated value or <see langword="default"/> if the union is empty.</param>'
W '    /// <returns><see langword="true"/> if the union encapsulates a non-<see langword="null"/> <typeparamref name="T"/>; otherwise, <see langword="false"/>.</returns>'
W '    [MethodImpl(MethodImplOptions.AggressiveInlining)]'
W '    public bool TryGetValue(out T value)'
W '    {'
W '        value = _v;'
W '        return _hasValue && _v is not null;'
W '    }'
W ''
W '    /// <summary>'
W '    /// Obtains a <see langword="string"/> representation of the encapsulated value or returns <see cref="LaquaiLibUnion.NoValue"/> if the union is empty.'
W '    /// </summary>'
W '    /// <returns>A <see langword="string"/> as specified.</returns>'
W '    public override string ToString() => _hasValue ? LaquaiLibUnion.ToString(in _v) : LaquaiLibUnion.NoValue;'
W '    /// <summary>'
W '    /// Computes a hash code for the value encapsulated in the union or returns 0 if the union is empty.'
W '    /// </summary>'
W '    /// <returns>An <see langword="int"/> that represents the hash code of the value or 0 if the union is empty.</returns>'
W '    public override int GetHashCode() => _hasValue ? EqualityComparer<T>.Default.GetHashCode(_v) : 0;'
W '    /// <summary>'
W '    /// Determines whether the specified <see langword="object"/> is equal to the encapsulated value in the union (or if the object is itself a union of the same type, whether their values are equal).'
W '    /// </summary>'
W '    /// <param name="obj">The <see langword="object"/> to compare with the current union.</param>'
W '    /// <returns><see langword="true"/> if the specified <see langword="object"/> is equal to the encapsulated value in the union; otherwise, <see langword="false"/>.</returns>'
W '    public override bool Equals([NotNullWhen(true)] object obj) => obj switch'
W '    {'
W '        Result<T> other => Equals(other),'
W '        T value => Equals(value),'
W '        _ => false'
W '    };'
W '    /// <summary>'
W '    /// Determines whether the specified <see cref="Result{T}"/> is equal to the encapsulated value in the union.'
W '    /// </summary>'
W '    /// <param name="other">The <see cref="Result{T}"/> to compare with the current union.</param>'
W '    /// <returns><see langword="true"/> if the specified <see cref="Result{T}"/> is equal to the encapsulated value in the union; otherwise, <see langword="false"/>.</returns>'
W '    public bool Equals(Result<T> other) => _hasValue == other._hasValue && EqualityComparer<T>.Default.Equals(_v, other._v);'
W '    /// <summary>'
W '    /// Determines whether the specified <typeparamref name="T"/> is equal to the encapsulated value in the union.'
W '    /// </summary>'
W '    /// <param name="other">The <typeparamref name="T"/> to compare with the current union.</param>'
W '    /// <returns><see langword="true"/> if the specified <typeparamref name="T"/> is equal to the encapsulated value in the union; otherwise, <see langword="false"/>.</returns>'
W '    public bool Equals(T other) => _hasValue ? EqualityComparer<T>.Default.Equals(_v, other) : other is null;'
W '    /// <summary>'
W '    /// Determines whether the underlying values of two <see cref="Result{T}"/> instances are equal.'
W '    /// </summary>'
W '    /// <param name="left">The first <see cref="Result{T}"/> instance to compare.</param>'
W '    /// <param name="right">The second <see cref="Result{T}"/> instance to compare.</param>'
W '    /// <returns><see langword="true"/> if the values of the two <see cref="Result{T}"/> instances are equal; otherwise, <see langword="false"/>.</returns>'
W '    public static bool operator ==(Result<T> left, Result<T> right) => left.Equals(right);'
W '    /// <summary>'
W '    /// Determines whether the specified <see cref="Result{T}"/> is equal to the specified <typeparamref name="T"/>.'
W '    /// </summary>'
W '    /// <param name="left">The first <see cref="Result{T}"/> instance to compare.</param>'
W '    /// <param name="right">The second <typeparamref name="T"/> instance to compare.</param>'
W '    /// <returns><see langword="true"/> if the values of the two instances are equal; otherwise, <see langword="false"/>.</returns>'
W '    public static bool operator ==(Result<T> left, T right) => left.Equals(right);'
W '    /// <summary>'
W '    /// Determines whether the specified <typeparamref name="T"/> is equal to the specified <see cref="Result{T}"/>.'
W '    /// </summary>'
W '    /// <param name="left">The first <typeparamref name="T"/> instance to compare.</param>'
W '    /// <param name="right">The second <see cref="Result{T}"/> instance to compare.</param>'
W '    /// <returns><see langword="true"/> if the values of the two instances are equal; otherwise, <see langword="false"/>.</returns>'
W '    public static bool operator ==(T left, Result<T> right) => right.Equals(left);'
W '    /// <summary>'
W '    /// Determines whether the underlying values of two <see cref="Result{T}"/> instances are not equal.'
W '    /// </summary>'
W '    /// <param name="left">The first <see cref="Result{T}"/> instance to compare.</param>'
W '    /// <param name="right">The second <see cref="Result{T}"/> instance to compare.</param>'
W '    /// <returns><see langword="true"/> if the values of the two <see cref="Result{T}"/> instances are not equal; otherwise, <see langword="false"/>.</returns>'
W '    public static bool operator !=(Result<T> left, Result<T> right) => !(left == right);'
W '    /// <summary>'
W '    /// Determines whether the specified <see cref="Result{T}"/> is not equal to the specified <typeparamref name="T"/>.'
W '    /// </summary>'
W '    /// <param name="left">The first <see cref="Result{T}"/> instance to compare.</param>'
W '    /// <param name="right">The second <typeparamref name="T"/> instance to compare.</param>'
W '    /// <returns><see langword="true"/> if the values of the two instances are not equal; otherwise, <see langword="false"/>.</returns>'
W '    public static bool operator !=(Result<T> left, T right) => !(left == right);'
W '    /// <summary>'
W '    /// Determines whether the specified <typeparamref name="T"/> is not equal to the specified <see cref="Result{T}"/>.'
W '    /// </summary>'
W '    /// <param name="left">The first <typeparamref name="T"/> instance to compare.</param>'
W '    /// <param name="right">The second <see cref="Result{T}"/> instance to compare.</param>'
W '    /// <returns><see langword="true"/> if the values of the two instances are not equal; otherwise, <see langword="false"/>.</returns>'
W '    public static bool operator !=(T left, Result<T> right) => !(left == right);'
W '}'

$ord = @('', 'first', 'second', 'third', 'fourth', 'fifth', 'sixth', 'seventh', 'eighth', 'ninth', 'tenth', 'eleventh', 'twelfth', 'thirteenth', 'fourteenth', 'fifteenth', 'sixteenth')

for ($n = 2; $n -le 16; $n++)
{
    $tps = (1..$n | ForEach-Object { "T$_" }) -join ', '
    $self = "OneOf<$tps>"
    $cref = "OneOf{$tps}"
    $doc = $true

    W '/// <summary>'
    W "/// Represents a union that encapsulates a value of exactly one of $n types or nothing at all."
    W '/// </summary>'
    for ($i = 1; $i -le $n; $i++) { W "/// <typeparam name=`"T$i`">The $($ord[$i]) type the union may encapsulate.</typeparam>" }
    W '[Union]'
    W "public readonly struct $self : IEquatable<$self>"
    W '{'
    for ($i = 1; $i -le $n; $i++) { W "    private readonly T$i _v$i;" }
    W '    private readonly byte _tag;'
    W ''
    for ($i = 1; $i -le $n; $i++)
    {
        if ($doc)
        {
            W '    /// <summary>'
            W "    /// Initializes a new <see cref=`"$cref`"/> encapsulating the specified <typeparamref name=`"T$i`"/> value."
            W '    /// </summary>'
            W '    /// <param name="value">The value to encapsulate.</param>'
        }
        W "    public OneOf(T$i value)"
        W '    {'
        W "        _v$i = value;"
        W "        _tag = $i;"
        W '    }'
    }
    W ''
    if ($doc)
    {
        W '    /// <summary>'
        W '    /// Gets the value encapsulated in the union or <see langword="null"/> if the union is empty. Boxing occurs for value type case types.'
        W '    /// </summary>'
    }
    W '    public object Value => _tag switch'
    W '    {'
    for ($i = 1; $i -le $n; $i++) { W "        $i => _v$i," }
    W '        _ => null'
    W '    };'
    if ($doc)
    {
        W '    /// <summary>'
        W '    /// Gets whether the union encapsulates a non-<see langword="null"/> value.'
        W '    /// </summary>'
    }
    W '    public bool HasValue => _tag switch'
    W '    {'
    for ($i = 1; $i -le $n; $i++) { W "        $i => _v$i is not null," }
    W '        _ => false'
    W '    };'
    W ''
    for ($i = 1; $i -le $n; $i++)
    {
        if ($doc)
        {
            W '    /// <summary>'
            W "    /// Gets whether the union encapsulates a <typeparamref name=`"T$i`"/> value."
            W '    /// </summary>'
        }
        W "    public bool IsT$i => _tag == $i;"
    }
    W ''
    for ($i = 1; $i -le $n; $i++)
    {
        if ($doc)
        {
            W '    /// <summary>'
            W "    /// Returns the value of the union's <typeparamref name=`"T$i`"/> case, which may be <see langword=`"null`"/>, or throws if the union does not hold that case."
            W '    /// </summary>'
            W "    /// <returns>The encapsulated <typeparamref name=`"T$i`"/> value.</returns>"
            W "    /// <exception cref=`"InvalidOperationException`">Thrown if the union does not hold the <typeparamref name=`"T$i`"/> case. A case constructed with <see langword=`"null`"/> returns that <see langword=`"null`"/> instead of throwing, even though <see cref=`"HasValue`"/> is <see langword=`"false`"/> for it.</exception>"
        }
        W '    [MethodImpl(MethodImplOptions.AggressiveInlining)]'
        W "    public T$i AsT$i() => _tag == $i ? _v$i : LaquaiLibUnion.ThrowNotHeld<T$i>();"
    }
    W ''
    for ($i = 1; $i -le $n; $i++)
    {
        if ($doc)
        {
            W '    /// <summary>'
            W "    /// Attempts to retrieve the <typeparamref name=`"T$i`"/> value encapsulated in the union."
            W '    /// </summary>'
            W "    /// <param name=`"value`">An <see langword=`"out`"/> variable that receives the encapsulated value or <see langword=`"default`"/> if the union does not encapsulate a <typeparamref name=`"T$i`"/>.</param>"
            W "    /// <returns><see langword=`"true`"/> if the union encapsulates a non-<see langword=`"null`"/> <typeparamref name=`"T$i`"/>; otherwise, <see langword=`"false`"/>.</returns>"
        }
        W '    [MethodImpl(MethodImplOptions.AggressiveInlining)]'
        W "    public bool TryGetValue(out T$i value)"
        W '    {'
        # only the ctor for case i ever writes _vi, so a failed probe always yields default
        W "        value = _v$i;"
        W "        return _tag == $i && _v$i is not null;"
        W '    }'
    }
    W ''
    if ($doc)
    {
        W '    /// <summary>'
        W '    /// Obtains a <see langword="string"/> representation of the encapsulated value or returns <see cref="LaquaiLibUnion.NoValue"/> if the union is empty.'
        W '    /// </summary>'
        W '    /// <returns>A <see langword="string"/> as specified.</returns>'
    }
    W '    public override string ToString() => _tag switch'
    W '    {'
    for ($i = 1; $i -le $n; $i++) { W "        $i => LaquaiLibUnion.ToString(in _v$i)," }
    W '        _ => LaquaiLibUnion.NoValue'
    W '    };'
    if ($doc)
    {
        W '    /// <summary>'
        W '    /// Computes a hash code for the value encapsulated in the union or returns 0 if the union is empty.'
        W '    /// </summary>'
        W '    /// <returns>An <see langword="int"/> that represents the hash code of the value or 0 if the union is empty.</returns>'
    }
    W '    public override int GetHashCode() => _tag switch'
    W '    {'
    for ($i = 1; $i -le $n; $i++) { W "        $i => EqualityComparer<T$i>.Default.GetHashCode(_v$i)," }
    W '        _ => 0'
    W '    };'
    if ($doc)
    {
        W '    /// <summary>'
        W '    /// Determines whether the specified <see langword="object"/> is equal to the encapsulated value in the union (or if the object is itself a union of the same type, whether their values are equal).'
        W '    /// </summary>'
        W '    /// <param name="obj">The <see langword="object"/> to compare with the current union.</param>'
        W '    /// <returns><see langword="true"/> if the specified <see langword="object"/> is equal to the encapsulated value in the union; otherwise, <see langword="false"/>.</returns>'
    }
    W '    public override bool Equals([NotNullWhen(true)] object obj) => obj switch'
    W '    {'
    W "        $self other => Equals(other),"
    for ($i = 1; $i -le $n; $i++) { W "        T$i v$i => Equals(v$i)," }
    W '        _ => false'
    W '    };'
    if ($doc)
    {
        W '    /// <summary>'
        W "    /// Determines whether the specified <see cref=`"$cref`"/> encapsulates a value equal to the one encapsulated in this union."
        W '    /// </summary>'
        W "    /// <param name=`"other`">The <see cref=`"$cref`"/> to compare with the current union.</param>"
        W '    /// <returns><see langword="true"/> if the values of the two unions are equal; otherwise, <see langword="false"/>.</returns>'
    }
    W "    public bool Equals($self other) => _tag == other._tag && _tag switch"
    W '    {'
    for ($i = 1; $i -le $n; $i++) { W "        $i => EqualityComparer<T$i>.Default.Equals(_v$i, other._v$i)," }
    W '        _ => true'
    W '    };'
    for ($i = 1; $i -le $n; $i++)
    {
        if ($doc)
        {
            W '    /// <summary>'
            W "    /// Determines whether the specified <typeparamref name=`"T$i`"/> is equal to the encapsulated value in the union."
            W '    /// </summary>'
            W "    /// <param name=`"other`">The <typeparamref name=`"T$i`"/> to compare with the current union.</param>"
            W '    /// <returns><see langword="true"/> if the specified value is equal to the encapsulated value in the union; otherwise, <see langword="false"/>.</returns>'
        }
        # overloads instead of IEquatable<Ti> implementations; those unify and trip CS0695
        W "    public bool Equals(T$i other) => _tag == $i && EqualityComparer<T$i>.Default.Equals(_v$i, other);"
    }
    if ($doc)
    {
        W '    /// <summary>'
        W "    /// Determines whether the underlying values of two <see cref=`"$cref`"/> instances are equal."
        W '    /// </summary>'
        W "    /// <param name=`"left`">The first <see cref=`"$cref`"/> instance to compare.</param>"
        W "    /// <param name=`"right`">The second <see cref=`"$cref`"/> instance to compare.</param>"
        W '    /// <returns><see langword="true"/> if the values of the two unions are equal; otherwise, <see langword="false"/>.</returns>'
    }
    W "    public static bool operator ==($self left, $self right) => left.Equals(right);"
    if ($doc)
    {
        W '    /// <summary>'
        W "    /// Determines whether the underlying values of two <see cref=`"$cref`"/> instances are not equal."
        W '    /// </summary>'
        W "    /// <param name=`"left`">The first <see cref=`"$cref`"/> instance to compare.</param>"
        W "    /// <param name=`"right`">The second <see cref=`"$cref`"/> instance to compare.</param>"
        W '    /// <returns><see langword="true"/> if the values of the two unions are not equal; otherwise, <see langword="false"/>.</returns>'
    }
    W "    public static bool operator !=($self left, $self right) => !left.Equals(right);"
    for ($i = 1; $i -le $n; $i++)
    {
        if ($doc)
        {
            W '    /// <summary>'
            W "    /// Determines whether the specified <see cref=`"$cref`"/> encapsulates a value equal to the specified <typeparamref name=`"T$i`"/>."
            W '    /// </summary>'
            W "    /// <param name=`"left`">The <see cref=`"$cref`"/> instance to compare.</param>"
            W "    /// <param name=`"right`">The <typeparamref name=`"T$i`"/> instance to compare.</param>"
            W '    /// <returns><see langword="true"/> if the values of the two instances are equal; otherwise, <see langword="false"/>.</returns>'
        }
        W "    public static bool operator ==($self left, T$i right) => left.Equals(right);"
        if ($doc)
        {
            W '    /// <summary>'
            W "    /// Determines whether the specified <see cref=`"$cref`"/> encapsulates a value not equal to the specified <typeparamref name=`"T$i`"/>."
            W '    /// </summary>'
            W "    /// <param name=`"left`">The <see cref=`"$cref`"/> instance to compare.</param>"
            W "    /// <param name=`"right`">The <typeparamref name=`"T$i`"/> instance to compare.</param>"
            W '    /// <returns><see langword="true"/> if the values of the two instances are not equal; otherwise, <see langword="false"/>.</returns>'
        }
        W "    public static bool operator !=($self left, T$i right) => !left.Equals(right);"
        if ($doc)
        {
            W '    /// <summary>'
            W "    /// Determines whether the specified <typeparamref name=`"T$i`"/> is equal to the value encapsulated in the specified <see cref=`"$cref`"/>."
            W '    /// </summary>'
            W "    /// <param name=`"left`">The <typeparamref name=`"T$i`"/> instance to compare.</param>"
            W "    /// <param name=`"right`">The <see cref=`"$cref`"/> instance to compare.</param>"
            W '    /// <returns><see langword="true"/> if the values of the two instances are equal; otherwise, <see langword="false"/>.</returns>'
        }
        W "    public static bool operator ==(T$i left, $self right) => right.Equals(left);"
        if ($doc)
        {
            W '    /// <summary>'
            W "    /// Determines whether the specified <typeparamref name=`"T$i`"/> is not equal to the value encapsulated in the specified <see cref=`"$cref`"/>."
            W '    /// </summary>'
            W "    /// <param name=`"left`">The <typeparamref name=`"T$i`"/> instance to compare.</param>"
            W "    /// <param name=`"right`">The <see cref=`"$cref`"/> instance to compare.</param>"
            W '    /// <returns><see langword="true"/> if the values of the two instances are not equal; otherwise, <see langword="false"/>.</returns>'
        }
        W "    public static bool operator !=(T$i left, $self right) => !right.Equals(left);"
    }
    W '}'
}

$text = ($L -join [System.Environment]::NewLine) + [System.Environment]::NewLine
$enc = [System.Text.UTF8Encoding]::new($true)
$out = Join-Path $PSScriptRoot 'NonBoxingUnions.cs'
[System.IO.File]::WriteAllText($out, $text, $enc)
Write-Output "wrote $($L.Count) lines to $out"
