<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFrameworks>net9.0-windows;net10.0-windows</TargetFrameworks>
        <UseWindowsForms>true</UseWindowsForms>
        <UseWPF>true</UseWPF>
        <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
        
        <EmitCompilerGeneratedFiles>True</EmitCompilerGeneratedFiles>
        <CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)Generated</CompilerGeneratedFilesOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.9" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="$(SolutionDir)multitarget\LaquaiLib.Windows\LaquaiLib.Windows.csproj" />
        <ProjectReference Include="$(SolutionDir)Test\TestCore\TestCore.csproj" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="$(SolutionDir)netstandard2.0\LaquaiLib.Analyzers\LaquaiLib.Analyzers.csproj" OutputItemType="Analyzer" TreatAsPackageReference="True" />
        <ProjectReference Include="$(SolutionDir)netstandard2.0\LaquaiLib.Analyzers.Shared\LaquaiLib.Analyzers.Shared.csproj" OutputItemType="Analyzer" TreatAsPackageReference="True" />
        <ProjectReference Include="$(SolutionDir)netstandard2.0\LaquaiLib.Analyzers.Fixes\LaquaiLib.Analyzers.Fixes.csproj" OutputItemType="Analyzer" TreatAsPackageReference="True" />
        <ProjectReference Include="$(SolutionDir)netstandard2.0\LaquaiLib.Generators\LaquaiLib.Generators.csproj" OutputItemType="Analyzer" TreatAsPackageReference="True" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Resources\" />
    </ItemGroup>

</Project>