<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
      <OutputType>Exe</OutputType>
      <TargetFramework>net11.0</TargetFramework>
      <IsPackable>false</IsPackable>
      <LangVersion>preview</LangVersion>
      <Nullable>disable</Nullable>
      <ImplicitUsings>enable</ImplicitUsings>

      <UseMicrosoftTestingPlatformRunner>True</UseMicrosoftTestingPlatformRunner>
  </PropertyGroup>

  <ItemGroup>
      <PackageReference Include="xunit.v3" Version="3.2.2" />
      <PackageReference Include="Microsoft.CodeAnalysis.CSharp.CodeRefactoring.Testing" Version="1.1.4" />
      <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.0.0" />
      <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
      <ProjectReference Include="$(SolutionDir)netstandard2.0\LaquaiLib.Analyzers.Fixes\LaquaiLib.Analyzers.Fixes.csproj" ReferenceOutputAssembly="true" />

      <Using Include="Xunit" />
      <Using Include="Microsoft.CodeAnalysis.CSharp.Testing" />
      <Using Include="Microsoft.CodeAnalysis.Testing" />
      <Using Include="LaquaiLib.Analyzers.Fixes.Refactorings" />
  </ItemGroup>

</Project>
